[package]
name = "mint_limit"
edition = "2024.beta"
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
supply_lock = { local = "../supply_lock" }

[addresses]
mint_limit = "0x0"
